### ISSUE TITLE
React proptypes migation

### ISSUE THREAD

**Issue by phgn0** [JFusco/react-autocomplete#3]
React 15.5 moved proptypes to its own module 'prop-types'.
Therefore react-predictive-input does not work with newer react versions.

[A few renames](https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-reactproptypes) should be sufficient to migrate.

Thanks for making this project :)

**Comment by JFusco** [comment]
Thanks for the reminder. I will update!

**Comment by JFusco** [comment]
@phgn0 
This is fixed in 1.2.6: https://github.com/JFusco/react-predictive-input/releases/tag/v1.2.6
